name = "mockql"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "MOCK_STORE_KV"
id = "8a0c301b4c18450f983dcb2af91a8fdb"

[observability.logs]
enabled = true
invocation_logs = true